### ISSUE TITLE
Review generating UA tags

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/msg#31]
Hi Baishan,

please could you review this commit but don't merge it yet?

https://github.com/GeoNet/msg/commit/2de8c065823fd0e2b7a52177ba9fed63ef735ca4

It should replicate the UA tag generation from quake-mmi.  If it checks out ok then you and I can plan how to use it to send a push payload to UA.

Thanks,
Geoff

**Comment by bpeng** [comment]
The functions look correct to me.
