### ISSUE TITLE
End of lines in the email message

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/msg#41]
Hi,

A user has requested CRLF in the email message to eqnews.  It is using LF at the moment.  The old system used CRLF so changing to this should be ok for existing users.  Please could you see if you can get the email message from AlertEqNews() to use CRLF and send @kfenaugh an example email to try out?

Thanks,
Geoff

**Comment by kfenaugh** [comment]
User has withdrawn feedback. All good.
