### ISSUE TITLE
Add UA tags for VAL?

### ISSUE THREAD

**Issue by junghao** [GeoNet/msg#50]
In order to do haz-ua-val-consumer, I'm going to compose
<pre>
func (v *VAL) AlertUAPush() (message string, tags []string);
</pre>
Is the "tags" return value needed?
It might be similar to quake's tags. eg:
<pre>
3@all
0@aucklandvolcanicfield
2@okataina
</pre>

And if we decided not to provide notification filter in our app now, simply make our app subscribes 0@all by default will work.

**Comment by gclitheroe** [comment]
I guess VAL alerting was solved a different way and we don't need this any more. Closing.
